### PR TITLE
Login cookie bug

### LINKED ISSUE #72: Login Needs to be clicked twice to successfully login
In master, if you have clear your cookies on your browser, and then try to login with a user you have made previously you will get an error saying:
image

This shows up if you try login once, but if you try to login a second time with the same credentials you will be successfully logged in.

### PR DESCRIPTION
**Pull request by KatherynRizek**
This PR fixes the need to login twice and also reroutes the user to the login page after they sign up (instead of the homepage)

### CODE REVIEW

File: ui/src/Login.tsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ function Login() {
         })
         .then((res) => {
           setCookie("userToken", res.headers["authorization"], { path: "/" });
-          let token = cookies.userToken.replace("Bearer ", "");
+          let token = res.headers["authorization"].replace("Bearer ", "");
```
Comment (KatherynRizek) [inline ui/src/Login.tsx:47]: This line change on my local allowed me to login immediately instead of twice. It does not fix the fact that the cookie isn't set until the user changes pages, but I believe this is okay since when the user successfully logs in, they are rerouted to a new page and the cookie is set there

**Review by spanjshiri — APPROVED** [review]
works for me

**Review by jphilly11 — APPROVED** [review]

**Review by mchughmk — APPROVED** [review]
